### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by guemax** [digital-logbook/logbook#6]
Possible configuration options (at least the ones I can think of at this moment):

```toml
[prompt]
format = "(logbook)"
add_newline = false

[profiles]
default = "programming"

[profiles.school]
path = "/home/guemax/logbook/profiles/school.csv"

[profiles.programming]
path = "/home/guemax/logbook/profiles/programming.csv"

[profiles.freetime]
path = "/home/guemax/logbook/profiles/freetime.csv"
```
